# ==========================================
# CONFIGMAP - Biến dùng chung (không nhạy cảm)
# ==========================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  FRONTEND_HOST: "http://localhost:30080"
  BACKEND_USER_URL: "http://user-service:8000"
  BACKEND_COURSE_URL: "http://course-service:8001"
  BACKEND_QUIZ_EXAM_URL: "http://quiz-exam-service:8002"
  BACKEND_LEARNING_PROGRESS_URL: "http://learning-progress-service:8003"
  STORAGE_API_URL: "http://storage-service:9000"

---
# ==========================================
# SECRET - backend-secrets (chung: SECRET_KEY, DB creds, config-service DATABASE_URL)
# ==========================================
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: YWJjMTIz
  SECRET_KEY: MjRiMGE4YzdhZDkyNWEzZTI0ZTk5Y2UzNmIzYzUzYjJiMzNiNTQyMDk4NjExY2IxNGZjMDIzNzBjNDRkYTM5MA==
  # config-service dùng biến DATABASE_URL riêng (không dùng DB_HOST/PORT/USER/PASS tách rời như 4 service kia)
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOmFiYzEyM0Bwb3N0Z3Jlczo1NDMyL2NvbmZpZ19kYg==

---
# ==========================================
# SECRET - app-db-secrets (DB URL riêng từng service + OAuth)
# ==========================================
apiVersion: v1
kind: Secret
metadata:
  name: app-db-secrets
type: Opaque
stringData:
  COURSES_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/course_db"
  USERS_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/user_db"
  QUIZS_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/quiz_exam_db"
  LEARNING_PROGRESS_DB_URL: "postgresql+psycopg2://postgres:B2305573@postgres:5432/learning_progress_db"
  CLIENT_ID: "<google_client_id>"
  CLIENT_SECRET_KEY: "<google_client_secret>"